
# 基本设置
title: OKX加密货币资讯站
SEOTitle: OKX加密货币资讯站 | 实时行情·兑换工具·OKX 指南
description: "面向中文用户的加密货币博客：覆盖比特币/以太坊等主流币的实时价格与行情分析，USDT与人民币、PKR、LKR、日元、加元等法币换算教程，OKX/欧易的注册登录、实名认证、返佣、手续费、OKX Pay 与信号交易等实操指南。"
url: "https://ozqjb362.github.io"
baseurl: ""
github_username:    ozqjb362
header-img: img/post-bg-desk.jpg

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10

# 插件
plugins:
  - jekyll-paginate

# 排除文件
exclude:
  - README.md
  - Gruntfile.js
  - package.json
  - node_modules
  - less
